config/routes.rb
Fourof::Application.routes.draw do
  resources :notfounds

  root 'welcome#index'
end

app/models/notfound.rb
class Notfound < ActiveRecord::Base
  has_attached_file :site_404,
                storage: :s3,
                styles: { medium: "300x300>", thumb: "100x100>" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notfounds_controller.rb
class NotfoundsController < ApplicationController
  before_action :set_notfound, only: [:show, :edit, :update, :destroy]

  # GET /notfounds
  # GET /notfounds.json
  def index
    @notfounds = Notfound.all
  end

  # GET /notfounds/1
  # GET /notfounds/1.json
  def show
  end

  # GET /notfounds/new
  def new
    @notfound = Notfound.new
  end

  # GET /notfounds/1/edit
  def edit
  end

  # POST /notfounds
  # POST /notfounds.json
  def create
    @notfound = Notfound.new(notfound_params)

    upload_image

    respond_to do |format|
      if @notfound.save
        format.html { redirect_to @notfound, notice: 'Notfound was successfully created.' }
        format.json { render action: 'show', status: :created, location: @notfound }
      else
        format.html { render action: 'new' }
        format.json { render json: @notfound.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notfounds/1
  # PATCH/PUT /notfounds/1.json
  def update
    respond_to do |format|
      if @notfound.update(notfound_params)
        format.html { redirect_to @notfound, notice: 'Notfound was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @notfound.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notfounds/1
  # DELETE /notfounds/1.json
  def destroy
    @notfound.destroy
    respond_to do |format|
      format.html { redirect_to notfounds_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notfound
      @notfound = Notfound.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notfound_params
      params.require(:notfound).permit(:site_url, :site_404)
    end

    def upload_image
      model = @notfound
      html  = "http://#{params[:notfound][:site_url]}/foodougbar"
      kit   = IMGKit.new(html)
      model.site_404 = StringIO.new(kit.to_img(:png))
      model.save
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/notfounds_helper.rb
module NotfoundsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fourof</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/notfounds/_form.html.erb
<!--  need this for form? >>> , url: notfounds_path, html: { multipart: true } -->
<%= form_for(@notfound) do |f| %>
  <% if @notfound.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notfound.errors.count, "error") %> prohibited this notfound from being saved:</h2>

      <ul>
      <% @notfound.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :site_url, "http://" %>
    <%= f.text_field :site_url %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notfounds/edit.html.erb
<h1>Editing notfound</h1>

<%= render 'form' %>

<%= link_to 'Show', @notfound %> |
<%= link_to 'Back', notfounds_path %>

app/views/notfounds/index.html.erb
<h1>Listing notfounds</h1>

<table>
  <thead>
    <tr>
      <th>Site url</th>
      <th>404 page</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @notfounds.each do |notfound| %>
      <tr>
        <td><%= notfound.site_url %></td>
        <td><%= image_tag notfound.site_404.url(:medium) %><td>
        <td><%= link_to 'Show', notfound %></td>
        <td><%= link_to 'Edit', edit_notfound_path(notfound) %></td>
        <td><%= link_to 'Destroy', notfound, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notfound', new_notfound_path %>

app/views/notfounds/new.html.erb
<h1>New notfound</h1>

<%= render 'form' %>

<%= link_to 'Back', notfounds_path %>

app/views/notfounds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Site url:</strong>
  <%= @notfound.site_url %><br>
  <%= image_tag @notfound.site_404.url %>
</p>

<%= link_to 'Edit', edit_notfound_path(@notfound) %> |
<%= link_to 'Back', notfounds_path %>

app/views/welcome/index.html.erb
<h2>Welcome Index page</h2>

<p>
  The time is now: <%= Time.now %>
</p>

<div>
  <%= link_to "Get a 404", new_notfound_path %>
</div>